# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:financedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=Admin@Zorvyn

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# JWT
app.jwt.secret=3b7e9f2a1c4d8e6f0a2b5c7d9e1f3a5b7c9d0e2f4a6b8c0d1e3f5a7b9c2d4e6f
app.jwt.expiration-ms=86400000

# App
spring.application.name=zorvyn-finance